export const DOCUMENT_SUFFIXES = "('.doc', '.docx', '.pdf')";

export const documentTextSource = [
  "def document_text(path):",
  "    suffix = path.suffix.lower()",
  "    if suffix == '.doc':",
  "        return subprocess.run(['antiword', '-m', 'UTF-8.txt', '-w', '0', str(path)],",
  "            check=True, capture_output=True, text=True, encoding='utf-8',",
  "            env={**os.environ, 'LC_ALL': 'C'}).stdout",
  "    if suffix == '.docx':",
  "        from docx import Document",
  "        from docx.table import Table",
  "        parts = []",
  "        for block in Document(path).iter_inner_content():",
  "            if isinstance(block, Table):",
  "                parts.extend(' | '.join(cell.text for cell in row.cells) for row in block.rows)",
  "            else:",
  "                parts.append(block.text)",
  "        return '\\n'.join(parts)",
  "    if suffix == '.pdf':",
  "        from pypdf import PdfReader",
  "        parts = []",
  "        for number, page in enumerate(PdfReader(path).pages, 1):",
  "            content = page.extract_text()",
  "            if not content or not content.strip():",
  "                raise ValueError('A page has no readable text. Scanned pages are unsupported.')",
  "            parts.append(f'Page {number}\\n{content}')",
  "        return '\\n\\n'.join(parts)",
  "    raise ValueError('unsupported_document')",
].join("\n");
