import { DOCUMENT_SUFFIXES, documentTextSource } from "./document-text-source.js";

export type InspectionName = "read" | "glob" | "grep" | "list";

// biome-ignore lint/complexity/noExcessiveLinesPerFunction: this is one bounded generated guest program.
export function inspectionSource(operation: InspectionName, params: unknown): string {
  return [
    "from pathlib import Path",
    "import codecs, fnmatch, json, os, re, subprocess, sys",
    `op = ${JSON.stringify(operation)}`,
    `args = json.loads(${JSON.stringify(JSON.stringify(params))})`,
    documentTextSource,
    "def document_lines(path, offset, limit):",
    "    info = path.stat()",
    "    key = f'{path}:{info.st_mtime_ns}:{info.st_size}'",
    "    cache = Path('/workspace/.garden-desk-tools/read-extracted.txt')",
    "    cached = cache.read_text(encoding='utf-8') if cache.exists() else ''",
    "    if cached.split(chr(10), 1)[0] != key:",
    "        cached = key + chr(10) + chr(10).join(document_text(path).splitlines())",
    "        cache.parent.mkdir(parents=True, exist_ok=True)",
    "        cache.write_text(cached, encoding='utf-8')",
    "    for number, line in enumerate(cached.split(chr(10))[1:], 1):",
    "        if offset <= number < offset + limit: print(f'{number}: {line}')",
    "def read_utf8_lines(path, offset, limit):",
    "    line_endings = tuple(map(chr, (10, 13, 11, 12, 28, 29, 30, 133, 8232, 8233)))",
    "    def stream(handle):\n        current_line = 1\n        after_cr = False\n        has_content = False\n        writing = False\n        decoder = codecs.getincrementaldecoder('utf-8')('strict')",
    "        def write(text):\n            nonlocal writing\n            if not writing:\n                sys.stdout.write(str(current_line) + ': ')\n                writing = True\n            sys.stdout.write(text)",
    "        def consume(text):\n            nonlocal current_line, after_cr, has_content, writing\n            start = 0\n            for index, character in enumerate(text):",
    "                if after_cr:",
    "                    after_cr = False",
    "                    if character == chr(10):",
    "                        start = index + 1",
    "                        continue",
    "                if character in line_endings:\n                    if start < index:\n                        has_content = True",
    "                    if offset <= current_line < offset + limit:",
    "                        write(text[start:index])",
    "                        sys.stdout.write(chr(10))",
    "                    current_line += 1\n                    after_cr = character == chr(13)\n                    has_content = False\n                    writing = False\n                    start = index + 1",
    "            if start < len(text):",
    "                has_content = True",
    "                if offset <= current_line < offset + limit:",
    "                    write(text[start:])",
    "        while chunk := handle.read(65536):\n            if b'\\0' in chunk: raise ValueError('read_requires_utf8_text')",
    "            consume(decoder.decode(chunk))\n            if current_line >= offset + limit: return",
    "        consume(decoder.decode(b'', final=True))",
    "        if has_content and offset <= current_line < offset + limit:",
    "            sys.stdout.write(chr(10))",
    "    try:",
    "        with path.open('rb') as handle:",
    "            decoder = codecs.getincrementaldecoder('utf-8')('strict')",
    "            while chunk := handle.read(65536):",
    "                if b'\\0' in chunk: raise ValueError('read_requires_utf8_text')",
    "                decoder.decode(chunk)",
    "            decoder.decode(b'', final=True)",
    "            handle.seek(0)",
    "            stream(handle)",
    "    except UnicodeDecodeError:",
    "        raise ValueError('read_requires_utf8_text') from None",
    "def safe(value, default='/source'):",
    "    raw = str(value or default)",
    "    path = Path(raw if raw.startswith('/') else '/source/' + raw)",
    "    resolved = path.resolve()",
    "    roots = (Path('/source'), Path('/workspace'), Path('/run/attachments'))",
    "    if resolved not in roots and not str(resolved).startswith(tuple(str(root) + '/' for root in roots)):",
    "        raise ValueError('path_outside_guest_roots')",
    "    return resolved",
    "root = safe(args.get('path'))",
    "if op == 'read':",
    "    offset = args.get('offset', 1)",
    "    limit = args.get('limit', 2000)",
    `    if root.suffix.lower() in ${DOCUMENT_SUFFIXES}: document_lines(root, offset, limit)`,
    "    else: read_utf8_lines(root, offset, limit)",
    "elif op == 'glob':",
    "    pattern = args['pattern']",
    "    for item in sorted(root.glob(pattern)): print(item)",
    "elif op == 'grep':",
    "    regex = re.compile(args['pattern'])",
    "    include = args.get('include', '*')",
    "    files = [root] if root.is_file() else sorted(p for p in root.rglob('*') if p.is_file() and fnmatch.fnmatch(p.name, include))",
    "    for item in files:",
    "        try:",
    "            for number, line in enumerate(item.read_text(errors='replace').splitlines(), 1):",
    "                if regex.search(line): print(f'{item}:{number}:{line}')",
    "        except OSError as error: print(f'{item}: {error}')",
    "else:",
    "    depth = args.get('depth', 2)",
    "    def walk(folder, level):",
    "        if level > depth: return",
    "        for item in sorted(folder.iterdir()):",
    "            print(str(item) + ('/' if item.is_dir() else ''))",
    "            if item.is_dir() and not item.is_symlink(): walk(item, level + 1)",
    "    if root.is_dir(): walk(root, 1)",
  ].join("\n");
}
