export type EditName = "write" | "edit";

export function editSource(operation: EditName, params: unknown): string {
  return [
    "from pathlib import Path",
    "import base64, difflib, json, sys",
    `op = ${JSON.stringify(operation)}`,
    `args = json.loads(${JSON.stringify(JSON.stringify(params))})`,
    "def text(name): return base64.b64decode(args[name]).decode('utf-8')",
    "path = Path(args['path'])",
    "if not path.resolve().as_posix().startswith('/workspace/'): sys.exit('unsupported_path: write and edit change only files under /workspace')",
    "if op == 'write':",
    "    data = text('content').encode('utf-8')",
    "    path.parent.mkdir(parents=True, exist_ok=True)",
    "    path.write_bytes(data)",
    "    print(f'wrote {len(data)} bytes to {path}')",
    "else:",
    "    before = path.read_bytes().decode('utf-8')",
    "    eol = '\\r\\n' if '\\r\\n' in before else '\\n'",
    "    old, new = (text(name).replace('\\r\\n', '\\n').replace('\\n', eol) for name in ('old', 'new'))",
    "    marks = {**dict.fromkeys(map(chr, [*range(0x2010, 0x2016), 0x2212]), '-'), **dict.fromkeys(map(chr, range(0x2018, 0x201c)), \"'\"), **dict.fromkeys(map(chr, range(0x201c, 0x2020)), '\"')}",
    "    loose = lambda line: ' '.join(line.translate(str.maketrans(marks)).split())",
    "    lines, want = before.splitlines(True), old.splitlines()",
    "    starts = range(len(lines) - len(want) + 1) if want else range(0)",
    "    match = lambda clean, i: all(clean(lines[i + j]) == clean(line) for j, line in enumerate(want))",
    "    first = next((i for clean in (str.rstrip, str.strip, loose) for i in starts if match(clean, i)), None)",
    "    if old in before:",
    "        after = before.replace(old, new, 1)",
    "    elif first is None:",
    "        sys.exit('edit_old_not_found: old is not in the file, even with whitespace ignored; read the file again')",
    "    else:",
    "        end = first + len(want)",
    "        ending = lines[end - 1][len(lines[end - 1].rstrip('\\r\\n')):]",
    "        lines[first:end] = [new.rstrip('\\r\\n') + ending] if new else []",
    "        after = ''.join(lines)",
    "    path.write_bytes(after.encode('utf-8'))",
    "    sys.stdout.writelines(difflib.unified_diff(before.splitlines(True), after.splitlines(True), str(path), str(path)))",
  ].join("\n");
}
